### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by balion** [piotrkilczuk/cmsplugin_gallery#52]
Django==3.1.6
django-cms==3.8.0
cmsplugin_gallery==1.1.7

> Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/cmsplugin_gallery/models.py", line 74, in <module>
    class Image(Orderable):
  File "/usr/local/lib/python3.8/site-packages/cmsplugin_gallery/models.py", line 97, in Image
    gallery = models.ForeignKey(GalleryPlugin, verbose_name=_("Gallery"))
TypeError: __init__() missing 1 required positional argument: 'on_delete'

After setting workaround from #51 cannot migrate due to error above.

**Comment by dext1mus** [comment]
I am having the exact same problem

**Comment by vinitkumar** [comment]
@dext1mus @balion This will be resolved in the PR #53

**Comment by vinitkumar** [comment]
Please update to 2.0.1 on the pypi and it should just work. We did a new release yesterday.
